// Module included in the following assemblies:
// * osd-whats-new.adoc

:_mod-docs-content-type: REFERENCE
[id="osd-q3-2024_{context}"]
= Q3 2024

[role="_abstract"]
The following items were added during the third quarter of 2024.

* ** Support for {gcp-short} A2 instance types with A100 80GB GPUs.** {product-title} on {GCP} now supports A2 instance types with A100 80GB GPUs. These instance types meet the specific requirements listed by IBM Watsonx.ai. For more information, see xref:../osd_architecture/osd_policy/osd-service-definition.adoc#gcp-compute-types_osd-service-definition[{gcp-full} compute types].

* **Expanded support for {gcp-short} standard instance types.** {product-title} on {GCP} now supports standard instance types for control plane and infrastructure nodes.
For more information, see xref:../osd_planning/osd-limits-scalability.adoc#control-plane-and-infra-node-sizing-and-scaling-sd_osd-limits-scalability[Control plane and infrastructure node sizing and scaling].

* **{product-title} regions added.** {product-title} on {GCP} is now available in the following additional regions:
+
--
** Melbourne (`australia-southeast2`)
** Milan (`europe-west8`)
** Turin (`europe-west12`)
** Madrid (`europe-southwest1`)
** Santiago (`southamerica-west1`)
** Doha (`me-central1`)
** Dammam (`me-central2`)
--
+
For more information about region availabilities, see xref:../osd_architecture/osd_policy/osd-service-definition.adoc#regions-availability-zones_osd-service-definition[Regions and availability zones].