// Module included in the following assemblies:
// * osd-whats-new.adoc

:_mod-docs-content-type: REFERENCE
[id="osd-q2-2025_{context}"]
= Q2 2025

[role="_abstract"]
The following items were added during the second quarter of 2025.

// * **{product-title} SDN network plugin blocks future major upgrades**
* **Updated version requirements for migration from OpenShift SDN to OVN-Kubernetes.**
Your cluster version must be 4.16.43 or above to initiate live migration from the OpenShift SDN network plugin to the OVN-Kubernetes network plugin.
+
If your cluster uses the OpenShift SDN network plugin, you cannot upgrade to future major versions of {product-title} without migrating to OVN-Kubernetes.
+
For more information about migrating to OVN-Kubernetes, see xref:../networking/ovn_kubernetes_network_provider/migrate-from-openshift-sdn-osd.adoc#migrate-from-openshift-sdn[Migrating from OpenShift SDN network plugin to OVN-Kubernetes network plugin].

* **New version of {product-title} available.** {product-title} on {gcp} and {product-title} on {aws} versions 4.19 are now available for new clusters.

* **Support for enabling and disabling Secure Boot for Shielded VMs on a per machine basis.**
{product-title} on {GCP} users can now enable or disable Secure Boot for Shielded VMs on a per machine basis. For more information, see xref:../osd_cluster_admin/osd_nodes/osd-managing-worker-nodes.adoc#osd-managing-worker-nodes[Managing compute nodes].